version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2228:2181"
    networks:
      - eventsgateway
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    ports:
      - "9192:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_CREATE_TOPICS: "sv-uploads-test:1:1"
      KAFKA_ADVERTISED_HOST_NAME: "${MY_IP}"
      KAFKA_ADVERTISED_PORT: 9192
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - eventsgateway
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4563-4584:4563-4584'
      - '8050:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    volumes:
      - '/private/tmp/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - eventsgateway
  spark-notebook:
    image: jupyter/all-spark-notebook
    ports:
      - '8888:8888'
    volumes:
      - ./spark-notebook/work:/home/jovyan/work
    networks:
      - eventsgateway
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778" 
      - "16686:16686"
      - "4317:4317"
    networks:
        - eventsgateway
      
networks:
  eventsgateway: 
    external:
      name: eventsgateway
