services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.15
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - eventsgateway

  kafka:
    image: confluentinc/cp-kafka:6.2.15 #Kafka 2.8
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: uploads-au_default:1:0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    depends_on:
      zookeeper:
        condition: service_started
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - eventsgateway

  eventsgateway-api:
    image: eventsgateway-server
    ports:
      - "5000:5000"
    depends_on:
      kafka:
        condition: service_healthy
    stop_grace_period: 30s
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5000" ]
      interval: 5s
      timeout: 10s
      retries: 10

    networks:
      - eventsgateway

networks:
  eventsgateway:
