scrape_configs:
  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9091']

# prometheus metrics
#  - job_name: 'prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:9090']
