name: Run tests
on:
  push:
jobs:
  tests:
    name: Run unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up ci
        run: make setup-ci
      - name: Test
        run: GOPATH=/home/runner/go make test
